### ISSUE TITLE
Module not found: Can't resolve 'material-ui/CircularProgress'

### ISSUE THREAD

**Issue by cannyedge34** [TeamWertarbyte/material-ui-image#14]
I'm using material-ui v1.0.0-beta.

Your component `<Image />` is loading `CircularProgress` component like this:

`import { CircularProgress } from 'material-ui'`

the error is here:

`var _CircularProgress = require('material-ui/CircularProgress');` in `node_modules/material-ui-image/lib/components/Image`

However in doc https://material-ui-1dab0.firebaseapp.com/demos/progress/, is like this:

`import { CircularProgress } from 'material-ui/Progress';`

Anyway, it doesn't work, same error. what am i missing?

Thank

**Comment by leMaik** [comment]
Are you using the `@next` version of material-ui-image?

**Comment by leMaik** [comment]
Thank you for reporting this! :+1: 

The relevant line is https://github.com/TeamWertarbyte/material-ui-image/blob/master/src/components/Image/Image.js#L3, would you mind creating a PR that fixes this issue? :)

**Comment by cannyedge34** [comment]
Sorry i'm late. I was going to change the code and i saw your email. :+1: . Version 3.0.0-pre.6 works like a charm :)

Thank you!
