### ISSUE TITLE
Module not found: Can't resolve 'material-ui/CircularProgress'

### ISSUE THREAD

**Issue by smarti57** [TeamWertarbyte/material-ui-image#15]
It looks like the material-ui-next folks are [considering](https://github.com/mui-org/material-ui/issues/9532) flattening this particular component from the /Progress folder (where it is in my latest installed version) to the root.  The material-ui-image component is looking for it in the root of material-ui and it doesn't seem to be there in the 1.0 (37) version.

**Comment by leMaik** [comment]
Thanks for reporting this issue, it was fixed in v1.0.0-pre.6, see #14
