### ISSUE TITLE
Image is not loading!

### ISSUE THREAD

**Issue by akata01** [TeamWertarbyte/material-ui-image#16]
import Image from "material-ui-image";

const Exercises = () => {
  return (
    <div>
      <Image
        src="https://bit.ly/2GjUWDP"
        alt="hello"
      />
      <h1>hello</h1>
    </div>
  );
};

export default Exercises;

Images just won't render. Whenever i try to add an image while working with material-ui, image just won't render. What is it that i'm doing wrong?

**Comment by akata01** [comment]
I realized this is not an issue related to material-ui-image package. I figured out i don't know how to render images in any react component.

**Comment by leMaik** [comment]
@akata01 You can't use bit.ly URLs as image URLs. 😉
