### ISSUE TITLE
Consider user-provided icon

### ISSUE THREAD

**Issue by albinekb** [TeamWertarbyte/material-ui-image#18]
Hello! Nice library you made here.

I'm using `mdi-material-ui` for icons in my app since it includes tons more icons, but this library requires me to use `@material-ui/icon`, and I don't want to have both, would it be possible to not use `@material-ui/icon` directly in here so it's compatible with more icon libraries? Bring your own 👍

**Comment by leMaik** [comment]
It is compatible with more icon libraries. Sure, we will force you to bundle one icon you might not need, but that's only a few bytes. You can still use both, and you won't have "both" but only the icons that are actually used (that's everything you use + the 1 icon we use).

**Comment by albinekb** [comment]
I'm deploying to Lambda where I have a size limitation of 50MB, adding the whole of @material-ui/icons adds some MB to the deployment, which is not needed, but without it my app won't start 👍 I think it would be nice if you allowed using other icon libraries without needing to have @material-ui/icons  as a dep 👍 If not, please close this and I'll make a fork that supports it 🙂

**Comment by leMaik** [comment]
Having to ship megabytes of icons for using one icons is a problem that a bundler like Webpack might solve. Inlining the icon would be a quick-and-dirty solution.
