### ISSUE TITLE
Not working with material-ui v1.0.0-rc

### ISSUE THREAD

**Issue by alexdrimbe** [TeamWertarbyte/material-ui-image#19]
The v1.0.0-rc.0 breaking change affects the material-ui-image component.

The diff
-import CircularProgress from '@material-ui/core/Progress/CircularProgress';
+import CircularProgress from '@material-ui/core/CircularProgress';

**Comment by leMaik** [comment]
Yup, we will port everything in the coming weeks. A PR would be _very_ appreciated. :+1:
