### ISSUE TITLE
Update dependency list to remove peer warning

### ISSUE THREAD

**Issue by dustingraves** [TeamWertarbyte/material-ui-image#21]
Latest version of @material-ui/icons is 2.x.x and a peer dependency warning pops up looking for 1.x.x

`npm WARN material-ui-image@3.0.0 requires a peer of @material-ui/icons@^1.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by stefensuhat** [comment]
+1 for this

**Comment by ciprianpatru** [comment]
we are now at allow @material-ui/icons@^3.0.0 as a peer dep
