### ISSUE TITLE
Arrow functions into render methods is not good idea, maybe you should use methods and delegate change state into them

### ISSUE THREAD

**Issue by ilyasf** [TeamWertarbyte/material-ui-image#22]
https://github.com/TeamWertarbyte/material-ui-image/blob/cbb79f2bc5bf96df204c775e157882c458c5e7aa/src/components/Image/Image.js#L92

**Comment by leMaik** [comment]
Fixed it… That said, writing this issue probably took you longer than fixing it. :wink:
