### ISSUE TITLE
Add Typescript Support with example :)

### ISSUE THREAD

**Issue by diegochavez** [TeamWertarbyte/material-ui-image#23]
Hello I'm glad to use your component it's pretty nice, I have some small contribution, I've created this typescript module to add the typescript support.

material-ui-image.d.ts
```javascript
declare module "material-ui-image" {
    import { ReactNode } from "react";
    export interface ImageProps {
        src: string,
        aspectRatio?: number,
        color?: string,
        disableError?: boolean,
        disableSpinner?: boolean,
        disableTransition?: boolean,
        errorIcon?: ReactNode,
        imageStyle?: object,
        loading?: ReactNode,
        onClick?: (event:any) => any,
        style?: object
    }
    export const ImageComponent: React.ComponentType<ImageProps>;
    export default ImageComponent;
}
```

**Comment by leMaik** [comment]
Great! :tada: Why not open a PR? There is no need to declare this as a module; you can just add a `.d.ts` file beside the `.js` file

**Comment by diegochavez** [comment]
Nice, Yeah I'll do the PR then 👍 I didn't know that is not needed the module, I added like this on my current ts project.
