### ISSUE TITLE
Auto detect aspectRatio from image dimension

### ISSUE THREAD

**Issue by DmitryNakhimovich** [TeamWertarbyte/material-ui-image#26]
I want to use the plugin in the gallery of pictures that have different linear dimensions. I would like the parameter 'aspectRatio' to automatically determine the ratio of the image and set the dimensions of the container not only (1/1). Is there such a built-in feature? Please give an example. Thank.

**Comment by saschb2b** [comment]
@DmitryNakhimovich Currently you can only pass a certain `aspectRatio` that you have to define. There is no built in feature for auto-detecting this, yet. I used this component for quite a while now and also think this would be a good idea. We would love to have a PR on that

**Comment by leMaik** [comment]
How are we going to detect the aspect ratio from an image that isn't even loaded yet? :thinking: If we do that, the component size would "jump" after loading.

**Comment by DmitryNakhimovich** [comment]
@leMaik This can be achieved by turning on the 'require'. It is possible to set additional props like 'width' and 'height' by default. I'm not sure, but the capabilities of webpack may solve this problem.

**Comment by saschb2b** [comment]
But this only works with local image not with external ones linked via url if I understand that right

**Comment by DmitryNakhimovich** [comment]
@saschb2b Unfortunately yes, you are right. This is possible only for local files( because we will not be able to find out any information about the picture without receiving it. Probably further development of this topic is not yet possible.

**Comment by saschb2b** [comment]
@DmitryNakhimovich then I will close this for now. This magic would be super cool if we can implement it. Reopen if you think you've got an idea on how to solve this issue with local and or external images. I will also think about this more
