### ISSUE TITLE
Transitions way too slow

### ISSUE THREAD

**Issue by BenWildeman** [TeamWertarbyte/material-ui-image#27]
having the image fading in over the course of 2.5 seconds is way too slow. the perceived load time for the user would make this feel clunky. it would be better to make the transition sub 1s by default, or give an option to customise the transition time

**Comment by saschb2b** [comment]
Sorry for the late reply. The fadeIn transition is exactly as google intended it to be. But you can just override the transition via the imageStyle prop.
The default value is
```
transition: 'filterBrightness 2.5s cubic-bezier(0.4, 0.0, 0.2, 1), filterSaturate 3s cubic-bezier(0.4, 0.0, 0.2, 1), opacity 2s cubic-bezier(0.4, 0.0, 0.2, 1)'
```
Note that there are three different animations with three different durations.
Do you have a better idea on how we can expose this to make it more custom? I'm not a big fan of exposing three different props for each transition type

**Comment by BenWildeman** [comment]
not sure where Google intended the motion speed to be 2.5 - 3s long but the speed specs suggest otherwise https://material.io/design/motion/speed.html

**Comment by leMaik** [comment]
Maybe something like `transitionDuration={{ brightness: 2500, saturation: 3, opacity: 2000 }}`?

**Comment by leMaik** [comment]
I just realized that our animation had incorrect timings (i.e. didn't match the graphs above) for as long as this component existed. :man_facepalming: 

Fixed that and added a `animationDuration` property to customize the animation duration (in milliseconds).
