### ISSUE TITLE
Right click menu

### ISSUE THREAD

**Issue by download13** [TeamWertarbyte/material-ui-image#28]
I noticed that this uses a div over the image (I assume as a placeholder so the layout doesn't change if the image doesn't display). The only issue with that is that it doesn't allow right clicking the image to get a context menu.

Maybe the placeholder div could be moved behind the image so we can click?

EDIT: Current workaround is to supply a `imageStyle={{zIndex: 1}}` prop which makes the image render above the div for display and interaction purposes.

**Comment by saschb2b** [comment]
Good point. I think we could completely unmount the blocking div node after the image is loaded. It's just there to display the loading spinner or error icon. Will check that or fix it via zIndex
