### ISSUE TITLE
Allow customizing the internal styles

### ISSUE THREAD

**Issue by alex-shamshurin** [TeamWertarbyte/material-ui-image#31]
```
<div style={{
          width: '100%',
          height: '100%',
          position: 'absolute',
          top: 0,
          left: 0,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          pointerEvents: 'none'
        }}>
```

They are not configurable

**Comment by leMaik** [comment]
These styles center the loading spinner and error icons. If you want, you can submit a PR to update this component to using `withStyles`, which would allow the styles to be customized.

**Comment by leMaik** [comment]
@alex-shamshurin This can now be done with `iconContainerStyle`.
