### ISSUE TITLE
Allow onload onerror handlers as props

### ISSUE THREAD

**Issue by rizzlesauce** [TeamWertarbyte/material-ui-image#32]
I want to be able to detect when the image is finished loading or had an error loading so I can do something about it in my application. I propose adding optional onLoad and onError function props to the component, which get called respectively when the image has finished loading or has had an error loading.

**Comment by leMaik** [comment]
Should be simple, just add the props and call them (if they are set) [here](https://github.com/TeamWertarbyte/material-ui-image/blob/master/src/components/Image/Image.js#L71). PR welcome! :+1:

**Comment by rizzlesauce** [comment]
Thanks for the quick response. Yep, I have a PR I started today. I'll
submit it after I test it out. Would this change require an update in
version number?

Ross

**Comment by leMaik** [comment]
Thank you! I'll bump the version after the PR is merged.

**Comment by rizzlesauce** [comment]
PR submitted: https://github.com/TeamWertarbyte/material-ui-image/pull/33
