### ISSUE TITLE
Deprecated lifecycle hooks are being used in material-ui-image

### ISSUE THREAD

**Issue by shiraze** [TeamWertarbyte/material-ui-image#35]
componentWillReceiveProps is deprecated and will be removed from the next major release of React while they are being used by Image.

I'm using material-ui-image@^3.2.0 and react@^16.9.0

Any page that uses Image shows the following warning:
![image](https://user-images.githubusercontent.com/9248719/63009039-a4ffe780-be7b-11e9-9c3a-2faa1fbf67e6.png)

**Comment by leMaik** [comment]
PR welcome :+1:
