### ISSUE TITLE
Package does not declare babel-runtime as a dependency

### ISSUE THREAD

**Issue by ChiralMichael** [TeamWertarbyte/material-ui-image#37]
Any package requiring material-ui-image without babel-runtime installed will see the following error:

```Module not found: Error: Can't resolve 'babel-runtime/core-js/object/get-prototype-of' in '[snipped]\node_modules\material-ui-image\lib\components\Image'```

This can be resolved by adding a package dependency on babel-runtime (or a peer dependency, if that's desired).

**Comment by ChiralMichael** [comment]
I can submit a PR if you'd like, but the omission is curious. I'm waiting to here whether this was intentional.

**Comment by leMaik** [comment]
This wasn't intentional, but I'd like to do some research and see how other libraries handle this. It affects all our libraries (I think).

**Comment by leMaik** [comment]
@ChiralMichael Allright: transform-runtime shouldn't be here in the first place. I'll update the babel configuration accordingly.

**Comment by ChiralMichael** [comment]
Thanks!
