### ISSUE TITLE
Missing onError and onLoad types

### ISSUE THREAD

**Issue by iJimmyWei** [TeamWertarbyte/material-ui-image#38]
When https://github.com/TeamWertarbyte/material-ui-image/commit/d3a13f8e6b30b2466d9e2e360ed43908e6e2df33 got added, the types were not.

I.e anyone using typescript will find that these methods are missing when in fact they are already implemented

**Comment by leMaik** [comment]
@iJimmyWei PR welcome :tada:

**Comment by kthyer** [comment]
I just want to add that the same issue applies to the "iconContainerStyle" prop.

**Comment by leMaik** [comment]
@iJimmyWei @kthyer Both is now fixed and released in [v3.2.3](https://github.com/TeamWertarbyte/material-ui-image/releases/tag/v3.2.3).

**Comment by tylim88** [comment]
@IeMaik

the onError type error return in 3.2.4, even typecast as any won't solve it, has to revert to 3.2.3

I am using create-react-app 4.0.0-next.98
typescript version is 4.0.3
