### ISSUE TITLE
Problem with onTouchTap while clicking on desktop

### ISSUE THREAD

**Issue by daralion** [TeamWertarbyte/material-ui-image#4]
Whenever I try to left click an Image, its onTouchTap function isn't fired. It works just fine with right clicks or mouse wheel clicks.

**Comment by saschb2b** [comment]
Does the storybook demo fire an action?
Which browser/version do you use so I can recreate the problem.

**Comment by daralion** [comment]
I tried it out with Google Chrome Version 56.0.2924.87, and with Microsoft Edge 38.14393.0.0. I didn't try out the storybook demo.

**Comment by saschb2b** [comment]
@daralion seem to have fixed it. Will just update the material-ui package and the publish an new version. Thanks.

**Comment by saschb2b** [comment]
@daralion  1.2.0 is live. Please report back if it solves your problem.

**Comment by daralion** [comment]
I'm doing a console log with the OnTouchTap event. Apparently the event is being called twice on left click, because the log shows up twice. I'm not sure if this was the case before, as I was using it to show/hide an element.

**Comment by saschb2b** [comment]
All good things are 3 right? Try again with 1.2.2.

**Comment by daralion** [comment]
Works perfect now. Thanks for your time.

**Comment by saschb2b** [comment]
Good to hear. Feel free to add feature request if you run into limitations.
