### ISSUE TITLE
Image alt text for accessibility requirements

### ISSUE THREAD

**Issue by yg-dba** [TeamWertarbyte/material-ui-image#40]
This package is really great!   I love the aspectRatio support, the spinning wheel and the fading in of the image.

I was so excited to start using it, but then I realized that it doesn't support alt text, which is required for accessibility support.

Can you please add this to the feature request? 

Thanks!

**Comment by leMaik** [comment]
We spread the props, you can pass an alt prop and it will be forwarded to the img: https://github.com/TeamWertarbyte/material-ui-image/blob/master/src/components/Image/Image.js#L127

**Comment by yg-dba** [comment]
Thank you for letting me know!!

I added @ts-ignore to keep typescript happy.

FYI, an npm install gives some warnings that peer dependencies are required at older versions.  The application I’m working on has these packages at a later version.

>> npm install
npm WARN material-ui-image@3.2.2 requires a peer of @material-ui/icons@^1.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN material-ui-image@3.2.2 requires a peer of @material-ui/core@^1.0.0 || ^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by leMaik** [comment]
@yg-dba Thanks for mentioning that issue and sorry for the late reply. I just updated the typings and peer dependency and released a new version. If you update, the warnings and TypeScript issues will be gone. :sunglasses:

**Comment by yg-dba** [comment]
Thank you so much!  

It’s such a well designed component!  It got a lot of oohs and aahs!  You did an amazing job on it!
