### ISSUE TITLE
Incompatible with Gatsby Build.

### ISSUE THREAD

**Issue by austonpramodh** [TeamWertarbyte/material-ui-image#43]
![image](https://user-images.githubusercontent.com/5049050/76349532-319a5780-6330-11ea-9548-1cb5b2c128de.png)

The opacity of the image doesn't change after the image is loaded successfully.

Template - https://github.com/gatsbyjs/gatsby-starter-default

**Comment by leMaik** [comment]
Fixed, see https://github.com/TeamWertarbyte/material-ui-image/issues/51#issuecomment-695840940
