### ISSUE TITLE
There should be an prop option to whether to stretch the image or not.

### ISSUE THREAD

**Issue by BhushanDangore** [TeamWertarbyte/material-ui-image#45]
Currently, the image gets stretched regardless of the aspect ratio of the images. There was an issue regarding this but that one is closed now because according to them we can't determine the aspect ratio of the image which is not even loaded and that is correct #26. But I think what we can do is rather than determining the width and height of the container we should shrink the image so that it will fit into that container. Currently, the image is using 100% width and height therefore it is stretching. if we change it to max-width and max-height the image gets fitted within the container without stretching. (Centering of the image also need to be done)
![Annotation 2020-03-21 121355](https://user-images.githubusercontent.com/34269298/77221195-824e5380-6b6d-11ea-80c0-b82baf0ee876.jpg)

**Comment by Cubxity** [comment]
@BhushanDangore this can be achieved by adding `imageStyle={{objectFit: "cover"}}`

**Comment by leMaik** [comment]
Thanks for the PR, @Cubxity :+1: I'll publish a new version.
