### ISSUE TITLE
Event is not passed to onLoad or onError props handler

### ISSUE THREAD

**Issue by aclement455** [TeamWertarbyte/material-ui-image#46]
As said in the title the event argument is not passed to the onLoad or onError method

Currently:

      handleLoadImage = () => {
        this.setState({ imageLoaded: true })
        if (this.props.onLoad) {
          this.props.onLoad()
        }
      }
    
      handleImageError = () => {
        if (this.props.src) {
          this.setState({ imageError: true })
          if (this.props.onError) {
            this.props.onError()
          }
        }
      }

Should be:

      handleLoadImage = (event) => {
        this.setState({ imageLoaded: true })
        if (this.props.onLoad) {
          this.props.onLoad(event)
        }
      }
    
      handleImageError = (event) => {
        if (this.props.src) {
          this.setState({ imageError: true })
          if (this.props.onError) {
            this.props.onError(event)
          }
        }
      }

**Comment by leMaik** [comment]
It now includes the event, unless the image was already loaded when the component was rendered (SSR, see #51) in which case onLoad/onError is called without an event because we don't have any.
