### ISSUE TITLE
Related projects

### ISSUE THREAD

**Issue by mbrookes** [TeamWertarbyte/material-ui-image#5]
Hi @saschb2b - came across by chance. Feel free to submit a PR for a 'related projects' entry in the MUI docs. 👍

**Comment by saschb2b** [comment]
@mbrookes Thanks :) We already added 3 projects to the related page. This project didn't seemed worthy for me for a PR yet. Will spice it up with some better customization options and make my PR for sure. It's really a pleasure for us to use material-ui. Excited for the next branch.

**Comment by mbrookes** [comment]
Sounds great! Any project that provides a use building block or example of a common pattern is a welcome addition to the list. A few more entries and we'll be able to start classifying it.
