### ISSUE TITLE
Image do not load, result on a eternal loading

### ISSUE THREAD

**Issue by leojnxs** [TeamWertarbyte/material-ui-image#6]
For some reason, the src parameter is not passed to the img tag.

```
{src && !this.state.imageError ? <img
          {...image}
          style={{
            ...styles.img,
            opacity: !this.state.imageLoaded ? 0 : 1,
            animation: !this.state.imageLoaded ? '' : 'filter-animation 1s',
            ...imageStyle
          }}
          onLoad={() => this.imageLoaded()}
          onError={() => this.setState({imageError: true})}
        /> : null
        }
```

But, when i added `src: {src}` before `onLoad: ...`, the image load ok.
```
{src && !this.state.imageError ? <img
          {...image}
          style={{
            ...styles.img,
            opacity: !this.state.imageLoaded ? 0 : 1,
            animation: !this.state.imageLoaded ? '' : 'filter-animation 1s',
            ...imageStyle
          }},
          src: {src},
          onLoad={() => this.imageLoaded()}
          onError={() => this.setState({imageError: true})}
        /> : null
        }
```

**Comment by leMaik** [comment]
The `src` prop is missing in your first code sample. Also, you've got a syntax error in the second one (`src: src` instead of `src={src}`.

**Comment by leojnxs** [comment]
@leMaik the first code example, is the original component code, check **image.js** inside **src** folder.

The second code is the changed code, and yeah, i'd forgot the curly braces on the example. Question edited

**Comment by leMaik** [comment]
@leojnxs Yes, also realized that after I submitted my comment. We'll look into this issue. :+1:

**Comment by leMaik** [comment]
@saschb2b Looks like this was introduced in c400338f87c83fd20826dc03bbccdd116325715f (replaced `...this.props` with `...image`, but `image` does not include `src`.

**Comment by leojnxs** [comment]
@leMaik thank you for your feedback. 
I figured the problem might be in the ... image, too.
I'll use the 1.1.0 version.

**Comment by leojnxs** [comment]
@leMaik, i have a clue about what is causing this bug. I google for `const {prop1, prop2, ...out} = this.props` and a i found this: http://stackoverflow.com/questions/28534344/javascript-var-left-props-this-props

If I understood correctly, this code `const {color, disableError, disableSpinner, errorSize, imageStyle, src, style, loadingSize, loadingStyle, onTouchTap, ...image} = this.props` return a object image without the left properties.

I've tested this:
```javascript
const {color, disableError, disableSpinner, errorSize, imageStyle, src, style, loadingSize, loadingStyle, onTouchTap, ...image} = this.props

console.log(image) // object
console.log(image.color) // undefined
```

```javascript
// Remove color and src
const {disableError, disableSpinner, errorSize, imageStyle, style, loadingSize, loadingStyle, onTouchTap, ...image} = this.props

console.log(image) // object
console.log(image.color) // "red"
console.log(image.src) // "http://image_url"
```

I have coded a workaround but i don't have privilegies to push to the repo.

I hope i have helped...

**Comment by leMaik** [comment]
@leojnxs Thanks a lot for your help, but we already found that out yesterday: :wink: 

>  ... but `image` does not include src

**Comment by leojnxs** [comment]
@leMaik, i have tried push the fix again, but, i'm still getting "Permission to TeamWertarbyte/material-ui-image.git denied to leojnxs." message.

**Comment by saschb2b** [comment]
@leojnxs That's not how pull requests work :D You create a fork, fix it in your fork and create a pull request with it. Documentation can be found here https://help.github.com/articles/creating-a-pull-request/. Otherwise I just fixed it. Will publish today after some cleanup.

**Comment by saschb2b** [comment]
@leojnxs please try version 1.3.0

**Comment by leojnxs** [comment]
@saschb2b its it... That's the solution... Thanks for your explanation about how PR works, too.

I've used another approach to fix the bug, but in the end it's the same thing.

I'm glad for help :)
