### ISSUE TITLE
React 17+ needs to be supported

### ISSUE THREAD

**Issue by modernlearner** [TeamWertarbyte/material-ui-image#70]
Recently I created a React project using the create-react-app tool and it set the react version to 17+. Unfortunately the package.json for this project uses `^16` which only allows React 16.y.z versions to be used.

I'm not sure how much of a change upgrading to React 17 would actually be for this package. I skimmed through their [ChangeLog](https://github.com/facebook/react/blob/master/CHANGELOG.md#1700-october-20-2020) and it looks like there isn't much impact but I'm not familiar with this code base.

**Comment by StanBondar** [comment]
+1. It is impossible to use material-ui-image with React 17+, please add support.

**Comment by yungrari** [comment]
Use with `--legacy-peer-deps`
